LineLength:
  Enabled: false
MethodLength:
  Enabled: false
AbcSize:
  Enabled: false
VariableName:
  Enabled: false
RedundantBegin:
  Enabled: false
AccessorMethodName:
  Enabled: false
GuardClause:
  Enabled: false
ParameterLists:
  Enabled: false
