#
# To use proxy fill in proxy variables in each suit and uncomment them
#
# The first suit can be run on open network out of box, but all others
# require a nexus url be placed in mirror attribute. To quickly add nexus
# url find and replace https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/
#
#
driver:
  name: vagrant
  driver_config:
  #  http_proxy: "http://myproxy.com:port"
  #  https_proxy: "http://myproxy.com:port"
  #  no_proxy: ".list,.ofdomains.com"
  customize:
    memory: 2048
    cpuexecutioncap: 70
platforms:
  - name: centos-7.2
    driver:
      vagrantfile_erb: Vagrantfile.erb


provisioner:
#  http_proxy: "http://myproxy.com:port"
#  https_proxy: "http://myproxy.com:port"
#  no_proxy: ".list,.ofdomains.com"
  name: chef_solo
  script: "bootstrap.sh"
  cookbook_files_glob: "**/*"
  require_chef_omnibus: 11.18.12
  solo_rb:
    verify_api_cert: true
    ssl_verify_mode: :verify_peer
    log_level: :info

suites:
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: Userbin8
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[download::add]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/Userbin8/serverspec/
    attributes:
      workorder:
        rfcCi:
          ciName: ""
          ciAttributes:
            source: "http://hg.openjdk.java.net/jdk8u/jdk8u/archive/jdk8u141-b15.tar.bz2"
            headers: "{}"
            path: "/tmp/jdk8u141-b15.tar.bz2"
            post_download_exec_cmd: "tar xvjf /tmp/jdk8u141-b15.tar.bz2"
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "openjdk"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jdk"
        sysdefault: "true"
        version: "8"
        uversion: ""
        enable_jce: "false"
        binpath: "/tmp/jdk8u141-b15.bin"
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: OracleJre6
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/OracleJre6/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "oracle"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jre"
        sysdefault: "true"
        version: "6"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: OracleJre7
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/OracleJre7/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "oracle"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jre"
        sysdefault: "true"
        version: "7"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: OracleJre8
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/OracleJre8/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "oracle"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jre"
        sysdefault: "true"
        version: "8"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: OracleJdk6
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/OracleJdk6/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "oracle"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jdk"
        sysdefault: "true"
        version: "6"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: OracleJdk7
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/OracleJdk7/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "oracle"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jdk"
        sysdefault: "true"
        version: "7"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: OracleJdk8
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/OracleJdk8/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "oracle"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jdk"
        sysdefault: "true"
        version: "8"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: OracleServerJre7
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/OracleJdk7/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "oracle"
        install_dir: "/usr/lib/jvm"
        jrejdk: "server-jre"
        sysdefault: "true"
        version: "7"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: OracleServerJre8
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/OracleJdk8/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "oracle"
        install_dir: "/usr/lib/jvm"
        jrejdk: "server-jre"
        sysdefault: "true"
        version: "8"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: openJdkJre6
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/openJdkJre6/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "openjdk"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jre"
        sysdefault: "true"
        version: "6"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: openJdkJre7
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/openJdkJre7/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "openjdk"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jre"
        sysdefault: "true"
        version: "7"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: openJdkJre8
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/openJdkJre8/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "openjdk"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jre"
        sysdefault: "true"
        version: "8"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: openJdkJdk6
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/openJdkJdk6/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "openjdk"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jdk"
        sysdefault: "true"
        version: "6"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: openJdkJdk7
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/openJdkJdk7/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "openjdk"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jdk"
        sysdefault: "true"
        version: "7"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
#------------------------------------------------------------------------------------------------------------------------------------------------------
  - name: openJdkJdk8
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[java::add]
    veridier:
      inspec_tests:
        - test/integration/openJdkJdk8/serverspec/
    attributes:
      workorder:
        services:
          mirror:
            some-cloud:
              ciAttributes:
                mirrors: "{\n              \"jdk\":\"https://nexus.example.com/nexus/somepath/$flavor/$jrejdk/$version/\"\n}"
        cloud:
          ciName: "some-cloud"
      user:
      app_name: "java"
      java:
        flavor: "openjdk"
        install_dir: "/usr/lib/jvm"
        jrejdk: "jdk"
        sysdefault: "true"
        version: "8"
        uversion: ""
        enable_jce: "false"
        binpath: ""
    chef_client:
      config:
        log_level: ":debug"
      #  http_proxy: "http://myproxy.com:port"
      #  https_proxy: "http://myproxy.com:port"
      #  no_proxy: ".list,.ofdomains.com"
# Kitchen yaml is very picky about the file path and name of your serverspec test file
# The path must match [COOKBOOK]/test/integration/[SUITES]/serverspec/*_spec.rb
# Globbing pattern to match files is "serverspec/*/*_spec.rb"
