---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  cookbook_files_glob: "**/*"
  require_chef_omnibus: 11.18.12
  solo_rb:
    verify_api_cert: true
    ssl_verify_mode: :verify_peer
    log_level: :info

platforms:
  - name: centos-7.2

suites:
  - name: add
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[file::add]
    attributes:
      workorder:
        rfcCi:
          ciAttributes:
            path: '/opt/logstash-forwarder/logstash-forwarder.conf'
            content: 'changeme'
            exec_cmd: ''
  - name: delete
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[file::add]
      - recipe[file::delete]
    attributes:
      workorder:
        rfcCi:
          ciAttributes:
            path: '/opt/logstash-forwarder/logstash-forwarder.conf'
