---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  cookbook_files_glob: "**/*"
  require_chef_omnibus: 11.18.12
  solo_rb:
    verify_api_cert: true
    ssl_verify_mode: :verify_peer
    log_level: :info

platforms:
  - name: centos-7.2

suites:
  - name: add
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[library::add]
    attributes:
      workorder:
        rfcCi:
          ciAttributes:
            packages: '["php", "zip", "ruby-2.0.0.648-29.el7"]'
  - name: delete
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[library::add]
      - recipe[library::delete]
    attributes:
      workorder:
        rfcCi:
          ciAttributes:
            packages: '["php", "zip", "ruby"]'
