driver:
  name: vagrant
provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18.12
  script: "bootstrap.sh"
platforms:
  - name: centos-7.2
suites:
  - name: addDownload
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[download::add]
    attributes:
      download:
        headers: ""
        path: "/tmp/download_file.tar.gz"
        basic_auth_password: ""
        basic_auth_user: ""
        checksum: ""
        source: "https://github.com/oneops/oneops-testing/raw/master/dummyRepo/dummy.tar.gz"
        post_download_exec_cmd: "cp /tmp/download_file.tar.gz /"
      workorder:
        rfcCi:
          ciAttributes:
            headers: ""
            source: "https://github.com/oneops/oneops-testing/raw/master/dummyRepo/dummy.tar.gz"
            path: "/tmp/download_file.tar.gz"
            basic_auth_password: ""
            basic_auth_user: ""
            checksum: ""
            post_download_exec_cmd: "cp /tmp/download_file.tar.gz /"
          ciName: "dummy"
