driver:
  name: vagrant
provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18.12
  script: "bootstrap.sh"
platforms:
  - name: centos-7.2
suites:
  - name: addCron
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[job::add]
    veridier:
      inspec_tests:
        - test/integration/addCron/serverspec
    attributes:
      job:
        variables: "{\"HOME\":\"\",\"SHELL\":\"/var/\",\"MAILTO\":\"\",\"PATH\":\"\"}"
        month: "*"
        hour: "*"
        weekday: "*"
        description: "testJob"
        cmd: "/usr/cronDir/test.sh"
        user: "root"
        day: "*"
        minute: "*"
      workorder:
        rfcCi:
          ciAttributes:
            variables: "{\"HOME\":\"\",\"SHELL\":\"/var/\",\"MAILTO\":\"\",\"PATH\":\"\"}"
            month: "*"
            hour: "*"
            weekday: "*"
            description: "testJob"
            cmd: "/usr/cronDir/test.sh"
            user: "root"
            day: "*"
            minute: "*"
          ciBaseAttributes:
            user: "root"
          ciName: "root"
  - name: updateCron
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[job::add]
      - recipe[job::update]
    veridier:
      inspec_tests:
        - test/integration/updateCron/serverspec
    attributes:
      job:
        variables: "{\"HOME\":\"\",\"SHELL\":\"/var/\",\"MAILTO\":\"\",\"PATH\":\"\"}"
        month: "5"
        hour: "5"
        weekday: "5"
        description: "testJob"
        cmd: "/usr/cronDir/test.sh"
        user: "root"
        day: "5"
        minute: "5"
      workorder:
        rfcCi:
          ciAttributes:
            variables: "{\"HOME\":\"\",\"SHELL\":\"/var/\",\"MAILTO\":\"\",\"PATH\":\"\"}"
            month: "5"
            hour: "5"
            weekday: "5"
            description: "testJob"
            cmd: "/usr/cronDir/test.sh"
            user: "root"
            day: "5"
            minute: "5"
          ciBaseAttributes:
            user: "root"
          ciName: "root"
  - name: replaceCron
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[job::add]
      - recipe[job::replace]
    veridier:
      inspec_tests:
        - test/integration/replaceCron/serverspec
    attributes:
      job:
        variables: "{\"HOME\":\"\",\"SHELL\":\"/var/\",\"MAILTO\":\"\",\"PATH\":\"\"}"
        month: "5"
        hour: "5"
        weekday: "5"
        description: "testJob"
        cmd: "/usr/cronNewDir/test.sh"
        user: "root"
        day: "5"
        minute: "5"
      workorder:
        rfcCi:
          ciAttributes:
            variables: "{\"HOME\":\"\",\"SHELL\":\"/var/\",\"MAILTO\":\"\",\"PATH\":\"\"}"
            month: "5"
            hour: "5"
            weekday: "5"
            description: "testJob"
            cmd: "/usr/cronNewDir/test.sh"
            user: "root"
            day: "5"
            minute: "5"
          ciBaseAttributes:
            cmd: "/usr/cronDir/test.sh"
            user: "root"
          ciName: "root"
  - name: deleteCron
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[job::add]
      - recipe[job::delete]
    veridier:
      inspec_tests:
        - test/integration/DeleteCron/serverspec
    attributes:
      job:
        variables: "{\"HOME\":\"\",\"SHELL\":\"/var/\",\"MAILTO\":\"\",\"PATH\":\"\"}"
        month: "5"
        hour: "5"
        weekday: "5"
        description: "testJob"
        cmd: "/usr/cronNewDir/test.sh"
        user: "root"
        day: "5"
        minute: "5"
      workorder:
        rfcCi:
          ciAttributes:
            variables: "{\"HOME\":\"\",\"SHELL\":\"/var/\",\"MAILTO\":\"\",\"PATH\":\"\"}"
            month: "5"
            hour: "5"
            weekday: "5"
            description: "testJob"
            cmd: "/usr/cronNewDir/test.sh"
            user: "root"
            day: "5"
            minute: "5"
          ciBaseAttributes:
            cmd: "/usr/cronDir/test.sh"
            user: "root"
          ciName: "root"